### ISSUE TITLE
Issue with gulp watch

### ISSUE THREAD

**Issue by D8ATech** [CodyHouse/codyhouse-framework#44]
I seem to be having a problem with gulp that I can't find an answer to after searching for more than an hour including the issue #6 that is closed.

1. I cloned the framework
2. I run `npm install` and wait for everything to complete
3. I run `npm run gulp watch` and the terminal just returns with no messages

**Environment**
```
Environment: OSX 10.15.2 (Catalina)
npm/npx --version : 6.13.6
node --version : v13.5.0
gulp --version : CLI version: 2.2.0, Local version: 4.0.2
```

**Error**
I tried just `gulp watch` and this shows the following error:
```
internal/fs/utils.js:229
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '**/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:886:3)
    at Object.getInstalledBinaries (**/node_modules/node-sass/lib/extensions.js:132:13)
    at foundBinariesList (**/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (**/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (**/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (**/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (**/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '**/node_modules/node-sass/vendor'
```
The ** in the path is just the path to where I am storing my test app

I checked and sure enough there is not a directory or file named vendor in the node-sass folder.

I purged my npm cache clean, updated all my global npm packages but nothing I do allows this to run.

**Notes:**
Simple clone of the framework.  No files have been changed and only the npm command has been run to install all the packages

**Question:**
It seems that the error is in fsutils.  But this package is not listed in the package.json so it must be a dependency

**Comment by sebastiano-guerriero** [comment]
Hi there! After step 3, if you add content to the index.html file, can you see it in the browser? The gulp file (browsersync) should open a new blank page in your browser.

ps: `gulp watch` is not necessary and will result in errors.

**Comment by claudia-romano** [comment]
Hi, I'm closing this issue for inactivity. If you are still experiencing the same problem, please feel free to reopen it. Cheers!
