### ISSUE TITLE
Problem with gulp watch

### ISSUE THREAD

**Issue by Zerbio** [CodyHouse/codyhouse-framework#53]
Hi, everything was working fine, then suddenly Gulp gives me a error, I don't know why.

I've tried everything, cache deletion, node_modules and package-lock.json deletion, even uninstalling Node completely, and I still get the same error when running 'npm run gulp watch':

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Proyectocarta@0.0.1 gulp: `gulp "watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Proyectocarta@0.0.1 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2020-05-20T14_22_32_342Z-debug.log
```

Content of the log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gulp',
1 verbose cli   'watch'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info lifecycle Proyectocarta@0.0.1~pregulp: Proyectocarta@0.0.1
6 info lifecycle Proyectocarta@0.0.1~gulp: Proyectocarta@0.0.1
7 verbose lifecycle Proyectocarta@0.0.1~gulp: unsafe-perm in lifecycle true
8 verbose lifecycle Proyectocarta@0.0.1~gulp: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Google Drive\Mis webs\Proyectocarta\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Usuario\bin;C:\PROGRAM FILES (X86)\COMMON FILES\ORACLE\JAVA\JAVAPATH;C:\RUBY24-X64\BIN;C:\RUBY25-X64\BIN;C:\PROGRAM FILES\COMMON FILES\MICROSOFT SHARED\WINDOWS LIVE;C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT SHARED\WINDOWS LIVE;C:\PROGRAM FILES (X86)\NVIDIA CORPORATION\PHYSX\COMMON;C:\Windows\SYSTEM32;C:\Windows;C:\Windows\SYSTEM32\WBEM;C:\Windows\SYSTEM32\WINDOWSPOWERSHELL\V1.0;C:\PROGRAM FILES\CALIBRE2;C:\PROGRAM FILES (X86)\ATI TECHNOLOGIES\ATI.ACE\CORE-STATIC;C:\PROGRAM FILES (X86)\WINDOWS LIVE\SHARED;C:\XAMPP\PHP;C:\PROGRAMDATA\COMPOSERSETUP\BIN;C:\PROGRAM FILES\GIT\CMD;C:\Program Files\ASUS\Bluetooth Software;C:\Program Files\ASUS\Bluetooth Software\syswow64;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\Usuario\AppData\Local\nylas\bin;C:\Users\Usuario\AppData\Roaming\Composer\vendor\bin;C:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Usuario\AppData\Roaming\npm
9 verbose lifecycle Proyectocarta@0.0.1~gulp: CWD: E:\Google Drive\Mis webs\Proyectocarta
10 silly lifecycle Proyectocarta@0.0.1~gulp: Args: [ '/d /s /c', 'gulp "watch"' ]
11 silly lifecycle Proyectocarta@0.0.1~gulp: Returned: code: 1  signal: null
12 info lifecycle Proyectocarta@0.0.1~gulp: Failed to exec gulp script
13 verbose stack Error: Proyectocarta@0.0.1 gulp: `gulp "watch"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid Proyectocarta@0.0.1
15 verbose cwd E:\Google Drive\Mis webs\Proyectocarta
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp" "watch"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error Proyectocarta@0.0.1 gulp: `gulp "watch"`
22 error Exit status 1
23 error Failed at the Proyectocarta@0.0.1 gulp script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Please, can you help me?

**Comment by claudia-romano** [comment]
Hey Zerbio,
did you make any specific changes to your project that trigger the error (e.g., installed new node modules, changed your project structure, etc)? Thanks.

**Comment by Zerbio** [comment]
No, nothing. I export from CodyHouse as usual, new package, run npm install, run 'npm run gulp watch' and error. I have also tried on a laptop, clean installation and the same thing happens to me.

I have been testing to see if I could find the problem. If I download the package without components or globals it seems not to give an error, if I enter elements after that it gives an error. But sometimes it does and sometimes it doesn't, I can't find the match.

I have also noticed that before the error occurs, all the CSS appears in the terminal.

![photo_2020-05-22_23-59-35](https://user-images.githubusercontent.com/13745280/82713209-77f22800-9c8a-11ea-9873-632311377b1e.jpg)

Components of the test package:

Flexi Header
Social Sharing
Smooth Scrolling
Reading Progress Bar
Sticky Headers Table
Back to Top
Main Footer V3

PD: Sorry for my English.

**Comment by claudia-romano** [comment]
Hi Zerbio,
are you downloading the project directly from the CodyHouse export page?
https://codyhouse.co/ds/export

If this is the case, could you get in touch at help@codyhouse.co with your email account and the name of project you are downloading? So that we can look into it.

Thanks.

**Comment by Zerbio** [comment]
Yes, of course. Ok, I'll send the email right now, thanks.

**Comment by claudia-romano** [comment]
Thanks! I'm closing this as the issue was solved. Cheers!
